version: '3.9'

volumes:
  mysql_data: #{}

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: leovv
      DB_PASSWORD: leovv
      DB_NAME: leovv
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes: 
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leovv
      MYSQL_USER: leovv
      MYSQL_PASSWORD: leovv
